/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_QLPKThuCung;

import Class_entity.NhanVien;

import TienIch.ImageHelper;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Dao.ThongKeDao;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import TienIch.Auth;
import TienIch.MsgBox;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import Dao.NhanVienDao;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import TienIch.MailSender;
import javax.swing.DefaultComboBoxModel;
import Dao.PhieuKhamDao;
import java.awt.Color;

/**
 *
 * @author minh
 */
public class BaoCaoThongKeDialog extends javax.swing.JDialog {

    /**
     * Creates new form BaoCaoThongKeDialog
     *
     * @param parent
     * @param modal
     */
    public BaoCaoThongKeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btntimkiem1 = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsaoluu = new javax.swing.JButton();
        btnsaoluu1 = new javax.swing.JButton();
        btnGuiMail = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLuongPKham = new javax.swing.JTable();
        btnsaoluu2 = new javax.swing.JButton();
        btnxoa1 = new javax.swing.JButton();
        btnsaoluu3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKEDoanhThu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        btnsaoluu4 = new javax.swing.JButton();
        btnxoa2 = new javax.swing.JButton();
        btnsaoluu5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(131, 26, 184));
        jLabel1.setText("BÁO CÁO THỐNG KÊ");

        tabs.setBackground(new java.awt.Color(140, 221, 227));

        jPanel2.setBackground(new java.awt.Color(128, 203, 225));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ NV", "TÊN NHÂN VIÊN", "TUỔI", "GIỚI TÍNH", "EMAIL", "LƯƠNG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setGridColor(new java.awt.Color(153, 0, 0));
        tblNhanVien.setRowHeight(25);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÌM KIẾM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btntimkiem1.setBackground(new java.awt.Color(128, 203, 225));
        btntimkiem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntimkiem1.setForeground(new java.awt.Color(0, 0, 204));
        btntimkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Search.png"))); // NOI18N
        btntimkiem1.setText("TÌM KIẾM");
        btntimkiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiem1ActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(128, 203, 225));
        btnxoa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(0, 153, 102));
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/print_anh.png"))); // NOI18N
        btnxoa.setText("Tải xuống");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsaoluu.setBackground(new java.awt.Color(128, 203, 225));
        btnsaoluu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnsaoluu.setForeground(new java.awt.Color(0, 153, 102));
        btnsaoluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/excel.png"))); // NOI18N
        btnsaoluu.setText("In ");
        btnsaoluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaoluuActionPerformed(evt);
            }
        });

        btnsaoluu1.setBackground(new java.awt.Color(128, 203, 225));
        btnsaoluu1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnsaoluu1.setForeground(new java.awt.Color(0, 153, 102));
        btnsaoluu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Exit.png"))); // NOI18N
        btnsaoluu1.setText("EXIT");
        btnsaoluu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaoluu1ActionPerformed(evt);
            }
        });

        btnGuiMail.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnGuiMail.setForeground(new java.awt.Color(0, 153, 102));
        btnGuiMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Gmail-icon.png"))); // NOI18N
        btnGuiMail.setText("@GMail");
        btnGuiMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btntimkiem1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuiMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsaoluu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsaoluu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnxoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsaoluu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsaoluu1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuiMail)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tabs.addTab("NHÂN VIÊN", jPanel2);

        jPanel4.setBackground(new java.awt.Color(128, 203, 225));

        tblLuongPKham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Năm", "Số pets khám", "Đầu tiên", "cuối cùng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLuongPKham.setRowHeight(25);
        jScrollPane3.setViewportView(tblLuongPKham);

        btnsaoluu2.setBackground(new java.awt.Color(128, 203, 225));
        btnsaoluu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Exit.png"))); // NOI18N
        btnsaoluu2.setText("EXIT");
        btnsaoluu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaoluu2ActionPerformed(evt);
            }
        });

        btnxoa1.setBackground(new java.awt.Color(128, 203, 225));
        btnxoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/print_anh.png"))); // NOI18N
        btnxoa1.setText("Tải xuống");
        btnxoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa1ActionPerformed(evt);
            }
        });

        btnsaoluu3.setBackground(new java.awt.Color(128, 203, 225));
        btnsaoluu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/excel.png"))); // NOI18N
        btnsaoluu3.setText("In ");
        btnsaoluu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaoluu3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsaoluu3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsaoluu2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnxoa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsaoluu3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsaoluu2)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        tabs.addTab("Lượng Pets Khám", jPanel4);

        jPanel3.setBackground(new java.awt.Color(128, 203, 225));

        tblThongKEDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên Dich vụ", "Số lượng nhân viên", "Số lượngphiếu khám", "Doanh Thu", "Thấp Nhất", "Cao Nhất", "Trung Bình"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblThongKEDoanhThu.setRowHeight(20);
        jScrollPane2.setViewportView(tblThongKEDoanhThu);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Năm:");

        cboNam.setPreferredSize(new java.awt.Dimension(58, 30));
        cboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamActionPerformed(evt);
            }
        });

        btnsaoluu4.setBackground(new java.awt.Color(128, 203, 225));
        btnsaoluu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Exit.png"))); // NOI18N
        btnsaoluu4.setText("EXIT");
        btnsaoluu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaoluu4ActionPerformed(evt);
            }
        });

        btnxoa2.setBackground(new java.awt.Color(128, 203, 225));
        btnxoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/print_anh.png"))); // NOI18N
        btnxoa2.setText("Tải xuống");
        btnxoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa2ActionPerformed(evt);
            }
        });

        btnsaoluu5.setBackground(new java.awt.Color(128, 203, 225));
        btnsaoluu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/excel.png"))); // NOI18N
        btnsaoluu5.setText("In ");
        btnsaoluu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaoluu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboNam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnxoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsaoluu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsaoluu4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnxoa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsaoluu5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsaoluu4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabs.addTab("DOANH THU", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaoluu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaoluu5ActionPerformed
        try {
            JFileChooser jFileChooser = new JFileChooser("D:\\");
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                FileOutputStream out;
                try ( XSSFWorkbook wb = new XSSFWorkbook()) {
                    org.apache.poi.ss.usermodel.Sheet sheet = wb.createSheet("Thống kê Doanh Thu");
                    Row rowcol = sheet.createRow(0);
                    for (int i = 0; i < tblNhanVien.getColumnCount(); i++) {
                        Cell cell = rowcol.createCell(i);
                        cell.setCellValue(tblNhanVien.getColumnName(i));
                    }
                    for (int j = 0; j < tblNhanVien.getRowCount(); j++) {
                        Row row = sheet.createRow(j + 1);
                        for (int k = 0; k < tblNhanVien.getColumnCount(); k++) {
                            Cell cell = row.createCell(k);
                            if (tblNhanVien.getValueAt(j, k) != null) {
                                cell.setCellValue(tblNhanVien.getValueAt(j, k).toString());
                            }
                        }
                    }
                    out = new FileOutputStream(new File(saveFile.toString()));
                    wb.write(out);
                }
                out.close();
                MsgBox.alert(null, "print thành công!");
                //  openFile(saveFile.toString());
            } else {
                MsgBox.alert(null, "print thất bại!");
            }
        } catch (HeadlessException e) {
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyThuCung.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QuanLyThuCung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaoluu5ActionPerformed

    private void btnxoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa2ActionPerformed
        row = tblNhanVien.getSelectedRow();

        MessageFormat header = new MessageFormat("Thống kê Doanh thu");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            tblNhanVien.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        } catch (PrinterException e) {
            MsgBox.alert(this, "Tải ảnh xuống không thành công");
        }                      // TODO add your handling code here:

    }//GEN-LAST:event_btnxoa2ActionPerformed

    private void btnsaoluu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaoluu4ActionPerformed
        this.thoat();
    }//GEN-LAST:event_btnsaoluu4ActionPerformed

    private void btnsaoluu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaoluu3ActionPerformed
        try {
            JFileChooser jFileChooser = new JFileChooser("D:\\");
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                FileOutputStream out;
                try ( XSSFWorkbook wb = new XSSFWorkbook()) {
                    org.apache.poi.ss.usermodel.Sheet sheet = wb.createSheet("Thống kê lượng pets Khám");
                    Row rowcol = sheet.createRow(0);

                    for (int i = 0; i < tblNhanVien.getColumnCount(); i++) {
                        Cell cell = rowcol.createCell(i);
                        tblLuongPKham.setForeground(Color.red);
                        cell.setCellValue(tblNhanVien.getColumnName(i));
                    }
                    for (int j = 0; j < tblNhanVien.getRowCount(); j++) {
                        Row row = sheet.createRow(j + 1);
                        for (int k = 0; k < tblNhanVien.getColumnCount(); k++) {
                            Cell cell = row.createCell(k);
                            if (tblNhanVien.getValueAt(j, k) != null) {
                                cell.setCellValue(tblNhanVien.getValueAt(j, k).toString());
                            }
                        }
                    }
                    out = new FileOutputStream(new File(saveFile.toString()));
                    wb.write(out);
                }
                out.close();
                MsgBox.alert(null, "print thành công!");
                //  openFile(saveFile.toString());
            } else {
                MsgBox.alert(null, "print thất bại!");
            }
        } catch (HeadlessException e) {
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyThuCung.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QuanLyThuCung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaoluu3ActionPerformed

    private void btnxoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa1ActionPerformed
        MessageFormat header = new MessageFormat("Thống kê Lượng pets khám");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            tblNhanVien.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        } catch (PrinterException e) {
            MsgBox.alert(this, "Tải ảnh xuống không thành công");
        }
    }//GEN-LAST:event_btnxoa1ActionPerformed

    private void btnsaoluu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaoluu2ActionPerformed
        this.thoat();
    }//GEN-LAST:event_btnsaoluu2ActionPerformed

    private void btnsaoluu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaoluu1ActionPerformed
        this.thoat();
    }//GEN-LAST:event_btnsaoluu1ActionPerformed

    private void btnsaoluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaoluuActionPerformed
        try {
            JFileChooser jFileChooser = new JFileChooser("D:\\");
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                FileOutputStream out;
                try ( XSSFWorkbook wb = new XSSFWorkbook()) {
                    org.apache.poi.ss.usermodel.Sheet sheet = wb.createSheet("Thống kê Nhân viên");
                    Row rowcol = sheet.createRow(0);
                    for (int i = 0; i < tblNhanVien.getColumnCount(); i++) {
                        Cell cell = rowcol.createCell(i);
                        cell.setCellValue(tblNhanVien.getColumnName(i));
                    }
                    for (int j = 0; j < tblNhanVien.getRowCount(); j++) {
                        Row row = sheet.createRow(j + 1);
                        for (int k = 0; k < tblNhanVien.getColumnCount(); k++) {
                            Cell cell = row.createCell(k);
                            if (tblNhanVien.getValueAt(j, k) != null) {
                                cell.setCellValue(tblNhanVien.getValueAt(j, k).toString());
                            }
                        }
                    }
                    out = new FileOutputStream(new File(saveFile.toString()));
                    wb.write(out);
                }
                out.close();
                MsgBox.alert(null, "print thành công!");
                //  openFile(saveFile.toString());
            } else {
                MsgBox.alert(null, "print thất bại!");
            }
        } catch (HeadlessException e) {
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLyThuCung.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QuanLyThuCung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaoluuActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        row = tblNhanVien.getSelectedRow();

        MessageFormat header = new MessageFormat("Thống kê nhân viên");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            tblNhanVien.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        } catch (PrinterException e) {
            MsgBox.alert(this, "Tải ảnh xuống không thành công");
        }                      // TODO add your handling code here:

    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimkiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiem1ActionPerformed
        row = tblNhanVien.getSelectedRow();
        this.timKiem();
    }//GEN-LAST:event_btntimkiem1ActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        row = tblNhanVien.getSelectedRow();
        this.search();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        //  row = tblNhanVien.getSelectedRow();

        this.row = tblNhanVien.getSelectedRow();

    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnGuiMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMailActionPerformed
        sendMail();
    }//GEN-LAST:event_btnGuiMailActionPerformed

    private void cboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamActionPerformed
        this.fillTableDoanhThu();
    }//GEN-LAST:event_cboNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BaoCaoThongKeDialog dialog = new BaoCaoThongKeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMail;
    private javax.swing.JButton btnsaoluu;
    private javax.swing.JButton btnsaoluu1;
    private javax.swing.JButton btnsaoluu2;
    private javax.swing.JButton btnsaoluu3;
    private javax.swing.JButton btnsaoluu4;
    private javax.swing.JButton btnsaoluu5;
    private javax.swing.JButton btntimkiem1;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxoa1;
    private javax.swing.JButton btnxoa2;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblLuongPKham;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblThongKEDoanhThu;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    ThongKeDao dao1 = new ThongKeDao();

    NhanVienDao dao = new NhanVienDao();
    int row = -1;

    void init() {
        this.setLocationRelativeTo(null);
        this.setTitle("BÁO CÁO THỐNG KÊ");
        this.setIconImage(ImageHelper.getAppIcon());
/////////////////////////////////////////////////    

        fillTableNhanVien();

        fillTableLuongPetsKham();
        fillComboBoxNam();
        fillTableDoanhThu();

////////////////////////////////////////////////
        this.selectTab(0);
        if (!Auth.isManager()) {
            tabs.remove(2);
        }

        tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(100);
        tblNhanVien.getColumnModel().getColumn(2).setMaxWidth(70);
        tblNhanVien.getColumnModel().getColumn(3).setMaxWidth(120);

        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);

        tblNhanVien.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        tblNhanVien.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblNhanVien.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblNhanVien.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        tblNhanVien.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        tblNhanVien.getColumnModel().getColumn(5).setCellRenderer(cellRenderer);

        tblLuongPKham.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        tblLuongPKham.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblLuongPKham.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblLuongPKham.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);

        tblThongKEDoanhThu.getColumnModel().getColumn(0).setMinWidth(100);
        tblThongKEDoanhThu.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblThongKEDoanhThu.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblThongKEDoanhThu.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        tblThongKEDoanhThu.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        tblThongKEDoanhThu.getColumnModel().getColumn(5).setCellRenderer(cellRenderer);
        tblThongKEDoanhThu.getColumnModel().getColumn(6).setCellRenderer(cellRenderer);
//        tblThongKEDoanhThu.getColumnModel().getColumn(7).setCellRenderer(cellRenderer);
//        tblThongKEDoanhThu.getColumnModel().getColumn(8).setCellRenderer(cellRenderer);
        // tblThongKEDoanhThu.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);

    }
    ///------------fillTableLuongPetsKham()--------------------------------------------

    public void fillTableLuongPetsKham() {
        DefaultTableModel model = (DefaultTableModel) tblLuongPKham.getModel();
        model.setRowCount(0);
        List<Object[]> list = dao1.getLuongPetsKham();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    //-----------------fillTableNhanVien()---------------------------------------
    void fillTableNhanVien() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        List<Object[]> list = dao1.getTK_NhanVien();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
///------------------selectTab--------------------------------------------

    public void selectTab(int row) {
        tabs.setSelectedIndex(row);
    }

    private void timKiem() {
        this.fillTableNhanVien();
        // this.clearForm();
        this.row = -1;

    }

    private void search() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblNhanVien.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText().trim()));

    }


    private void thoat() {
        this.dispose();
    }

    void sendMail() {
        if (tblNhanVien.getRowCount() == 0) {
            MsgBox.alert(this, "Không có Nhân viên nào");
            return;
        }

        new Thread(() -> {
            for (int i = 0; i < tblNhanVien.getRowCount(); i++) {
                String maNV = tblNhanVien.getValueAt(i, 0).toString();
                NhanVien nh = new NhanVienDao().selectById(maNV);
                String Luong = tblNhanVien.getValueAt(i, 2) == null ? "chưa có" : tblNhanVien.getValueAt(i, 5).toString();
                String Mã = tblNhanVien.getValueAt(i, 2) == null ? "chưa có" : tblNhanVien.getValueAt(i, 0).toString();
                String mess = "\n => Mã nhân viên của bạn " + "\n" + Mã + "\r => Lương của Bạn " + nh.getHoTen() + " \n là " + Luong + ".VNĐ";

                MailSender.send("thangttps16989@fpt.edu.vn", "happy2002", "Thông báo Lương", mess, nh.getEmail());
                //  MsgBox.alert(null, "Gửi Thành công ! " +Mã);
            }
        }).start();

//         WaitingJDialog w = new WaitingJDialog(null, true, tblNhanVien.getRowCount());
//        w.setVisible(true);
        MsgBox.alert(null, "Gửi Thành công ! ");
    }

    //-------------------------FILL COMBOX NAM -------------------------------------------------------
    PhieuKhamDao PKdao = new PhieuKhamDao();

    void fillComboBoxNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboNam.getModel();
        model.removeAllElements();
        List<Integer> list = PKdao.selectYears();
        for (Integer year : list) {
            model.addElement(year);
        }
    }

    void fillTableDoanhThu() {
        DefaultTableModel model = (DefaultTableModel) tblThongKEDoanhThu.getModel();
        model.setRowCount(0);
        int nam1 = (Integer) cboNam.getSelectedItem();
//   int nam1 =  (int) cboNam.getSelectedItem();
        List<Object[]> list = dao1.getDoanhThu(nam1);
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

}// 

