/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_QLPKThuCung;

import TienIch.ImageHelper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import TienIch.Auth;
import TienIch.MsgBox;
import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class Form_HeThongChinh extends javax.swing.JFrame {

    /**
     * Creates new form Form_HeThongChinh
     */
    public Form_HeThongChinh() {
        initComponents();
        this.setTitle("HỆ THỐNG PHÒNG KHÁM THÚ CƯNG");
        this.init();
        this.iiinit();

    }

    void iiinit() {

        lblDangHoatDong.setText("Đang hoạt động.....!");

        lbhethongquanlipet.setText(Auth.user!=null?Auth.user.getMaNV():"khách");

        lbhethongquanlipet.setIcon(new ImageIcon("src\\Image\\icon\\user.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbquangliphongkhampet = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        blthongke2 = new javax.swing.JLabel();
        lbthongke1 = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        lbhoadon = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbphieukham = new javax.swing.JLabel();
        lblPhieuKham = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbquanlithongtinpet = new javax.swing.JLabel();
        lblThuCung = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbquanlithuoc = new javax.swing.JLabel();
        lblQunaLyThuoc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnkhamdinhki = new javax.swing.JButton();
        btnphauthuatchomeo = new javax.swing.JButton();
        btnkhachsan = new javax.swing.JButton();
        btnrangmieng = new javax.swing.JButton();
        btncapcuu = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lbAnh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblDangHoatDong = new javax.swing.JLabel();
        lbhethongquanlipet = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miDangnhap = new javax.swing.JMenuItem();
        miQuenMatKhau = new javax.swing.JMenuItem();
        midoimatkhau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        midichvu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mikethuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        minihoadon = new javax.swing.JMenuItem();
        miniphieukham = new javax.swing.JMenuItem();
        miniquanlithongtinpet = new javax.swing.JMenuItem();
        miniquanlithuoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        miniQuanLyThongTin = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miniNhanVien = new javax.swing.JMenuItem();
        miniLuongThuCungKham = new javax.swing.JMenuItem();
        minibaocaothongke = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        minilienhe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(158, 235, 241));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(97, 95, 95));

        lbquangliphongkhampet.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbquangliphongkhampet.setForeground(new java.awt.Color(255, 255, 255));
        lbquangliphongkhampet.setText("QUẢN LÍ PHÒNG KHÁM PET");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lbquangliphongkhampet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbquangliphongkhampet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(33, 152, 122));

        blthongke2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        blthongke2.setForeground(new java.awt.Color(255, 255, 255));
        blthongke2.setText("THỐNG KÊ");
        blthongke2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                blthongke2MouseMoved(evt);
            }
        });
        blthongke2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blthongke2MouseClicked(evt);
            }
        });

        lbthongke1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/thống kê.png"))); // NOI18N
        lbthongke1.setText("jLabel12");
        lbthongke1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbthongke1MouseMoved(evt);
            }
        });
        lbthongke1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbthongke1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbthongke1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbthongke1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(blthongke2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbthongke1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blthongke2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHoaDon.setBackground(new java.awt.Color(199, 165, 90));

        lbhoadon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbhoadon.setForeground(new java.awt.Color(255, 255, 255));
        lbhoadon.setText("HÓA ĐƠN");
        lbhoadon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbhoadonMouseMoved(evt);
            }
        });
        lbhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbhoadonMouseClicked(evt);
            }
        });

        lblHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/hóa đơn.png"))); // NOI18N
        lblHoaDon.setText("jLabel11");
        lblHoaDon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseMoved(evt);
            }
        });
        lblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbhoadon)
                    .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHoaDon)
                .addGap(18, 18, 18)
                .addComponent(lbhoadon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(209, 188, 171));

        lbphieukham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbphieukham.setForeground(new java.awt.Color(255, 255, 255));
        lbphieukham.setText("PHIẾU KHÁM");
        lbphieukham.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbphieukhamMouseMoved(evt);
            }
        });
        lbphieukham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbphieukhamMouseClicked(evt);
            }
        });

        lblPhieuKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/phiếu khám.png"))); // NOI18N
        lblPhieuKham.setText("jLabel15");
        lblPhieuKham.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblPhieuKhamMouseMoved(evt);
            }
        });
        lblPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhieuKhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbphieukham)
                    .addComponent(lblPhieuKham, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhieuKham, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lbphieukham)
                .addGap(113, 113, 113))
        );

        jPanel7.setBackground(new java.awt.Color(148, 137, 137));

        lbquanlithongtinpet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbquanlithongtinpet.setForeground(new java.awt.Color(255, 255, 255));
        lbquanlithongtinpet.setText("QL THÔNG TIN PET");
        lbquanlithongtinpet.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbquanlithongtinpetMouseMoved(evt);
            }
        });
        lbquanlithongtinpet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbquanlithongtinpetMouseClicked(evt);
            }
        });

        lblThuCung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/quản lsi thông tin pet.png"))); // NOI18N
        lblThuCung.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThuCungMouseMoved(evt);
            }
        });
        lblThuCung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuCungMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblThuCung)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbquanlithongtinpet)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lbquanlithongtinpet)
                .addGap(22, 22, 22))
        );

        jPanel8.setBackground(new java.awt.Color(166, 198, 177));

        lbquanlithuoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbquanlithuoc.setForeground(new java.awt.Color(255, 255, 255));
        lbquanlithuoc.setText("QUẢN LÍ THUỐC");
        lbquanlithuoc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbquanlithuocMouseMoved(evt);
            }
        });
        lbquanlithuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbquanlithuocMouseClicked(evt);
            }
        });

        lblQunaLyThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/quản lí thuốc.png"))); // NOI18N
        lblQunaLyThuoc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQunaLyThuocMouseMoved(evt);
            }
        });
        lblQunaLyThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQunaLyThuocMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lbquanlithuoc)
                .addGap(21, 21, 21))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblQunaLyThuoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQunaLyThuoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbquanlithuoc)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(110, 110, 223))); // NOI18N

        btnkhamdinhki.setBackground(new java.awt.Color(0, 153, 0));
        btnkhamdinhki.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnkhamdinhki.setForeground(new java.awt.Color(255, 255, 255));
        btnkhamdinhki.setText(" Khám sức khỏe định kỳ");
        btnkhamdinhki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhamdinhkiActionPerformed(evt);
            }
        });

        btnphauthuatchomeo.setBackground(new java.awt.Color(0, 153, 0));
        btnphauthuatchomeo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnphauthuatchomeo.setForeground(new java.awt.Color(255, 255, 255));
        btnphauthuatchomeo.setText("Tiểu phẩu,Đại phẩu cho chó mèo");
        btnphauthuatchomeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphauthuatchomeoActionPerformed(evt);
            }
        });

        btnkhachsan.setBackground(new java.awt.Color(0, 153, 0));
        btnkhachsan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnkhachsan.setForeground(new java.awt.Color(255, 255, 255));
        btnkhachsan.setText("Khách sạn chó mèo");
        btnkhachsan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachsanActionPerformed(evt);
            }
        });

        btnrangmieng.setBackground(new java.awt.Color(0, 153, 0));
        btnrangmieng.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnrangmieng.setForeground(new java.awt.Color(255, 255, 255));
        btnrangmieng.setText("Chăm sóc răng miệng");
        btnrangmieng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrangmiengActionPerformed(evt);
            }
        });

        btncapcuu.setBackground(new java.awt.Color(0, 153, 0));
        btncapcuu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btncapcuu.setForeground(new java.awt.Color(255, 255, 255));
        btncapcuu.setText("Cấp cứu 24/7");
        btncapcuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapcuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnkhamdinhki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnphauthuatchomeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkhachsan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrangmieng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncapcuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnkhamdinhki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnphauthuatchomeo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkhachsan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnrangmieng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncapcuu)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        lbAnh.setBackground(new java.awt.Color(255, 255, 255));
        lbAnh.setForeground(new java.awt.Color(51, 0, 51));
        lbAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Anh/images.jpg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Bell.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lbAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblDangHoatDong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDangHoatDong.setForeground(new java.awt.Color(0, 0, 255));

        lbhethongquanlipet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbhethongquanlipet.setForeground(new java.awt.Color(45, 64, 151));
        lbhethongquanlipet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Info.png"))); // NOI18N
        lbhethongquanlipet.setText("Hệ thống phòng khám thú cưng ^.^ của Nhóm 6");

        lblDongHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(45, 64, 151));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Alarm.png"))); // NOI18N
        lblDongHo.setText("00:00:00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbhethongquanlipet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDangHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDangHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDongHo)
                    .addComponent(lbhethongquanlipet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 204));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Hệ thống.png"))); // NOI18N
        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miDangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miDangnhap.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        miDangnhap.setForeground(new java.awt.Color(236, 114, 36));
        miDangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Key.png"))); // NOI18N
        miDangnhap.setText("Đăng Xuất");
        miDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDangnhapActionPerformed(evt);
            }
        });
        jMenu1.add(miDangnhap);

        miQuenMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        miQuenMatKhau.setForeground(new java.awt.Color(236, 114, 36));
        miQuenMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Accept.png"))); // NOI18N
        miQuenMatKhau.setText("Quên mật khẩu");
        miQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuenMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(miQuenMatKhau);

        midoimatkhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        midoimatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        midoimatkhau.setForeground(new java.awt.Color(236, 114, 36));
        midoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/DoiMatKhau.png"))); // NOI18N
        midoimatkhau.setText("Đổi mật khẩu");
        midoimatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                midoimatkhauMouseClicked(evt);
            }
        });
        midoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midoimatkhauActionPerformed(evt);
            }
        });
        jMenu1.add(midoimatkhau);
        jMenu1.add(jSeparator1);

        midichvu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        midichvu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        midichvu.setForeground(new java.awt.Color(236, 114, 36));
        midichvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/dịch vụ.png"))); // NOI18N
        midichvu.setText("Dịch vụ");
        midichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midichvuActionPerformed(evt);
            }
        });
        jMenu1.add(midichvu);
        jMenu1.add(jSeparator2);

        mikethuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mikethuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mikethuc.setForeground(new java.awt.Color(236, 114, 36));
        mikethuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Exit.png"))); // NOI18N
        mikethuc.setText("Kết thúc");
        mikethuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mikethucActionPerformed(evt);
            }
        });
        jMenu1.add(mikethuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 204));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/quản lý.png"))); // NOI18N
        jMenu2.setText("Quản lí");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        minihoadon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        minihoadon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        minihoadon.setForeground(new java.awt.Color(236, 114, 36));
        minihoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Price list.png"))); // NOI18N
        minihoadon.setText("Hóa đơn");
        minihoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minihoadonActionPerformed(evt);
            }
        });
        jMenu2.add(minihoadon);

        miniphieukham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miniphieukham.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        miniphieukham.setForeground(new java.awt.Color(236, 114, 36));
        miniphieukham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/List.png"))); // NOI18N
        miniphieukham.setText("Phiếu khám");
        miniphieukham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniphieukhamActionPerformed(evt);
            }
        });
        jMenu2.add(miniphieukham);

        miniquanlithongtinpet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miniquanlithongtinpet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        miniquanlithongtinpet.setForeground(new java.awt.Color(236, 114, 36));
        miniquanlithongtinpet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Dog.png"))); // NOI18N
        miniquanlithongtinpet.setText("Quản lí thông tin Pet");
        miniquanlithongtinpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniquanlithongtinpetActionPerformed(evt);
            }
        });
        jMenu2.add(miniquanlithongtinpet);

        miniquanlithuoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miniquanlithuoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        miniquanlithuoc.setForeground(new java.awt.Color(236, 114, 36));
        miniquanlithuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Create.png"))); // NOI18N
        miniquanlithuoc.setText("Quản lí thuốc");
        miniquanlithuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniquanlithuocActionPerformed(evt);
            }
        });
        jMenu2.add(miniquanlithuoc);
        jMenu2.add(jSeparator3);

        miniQuanLyThongTin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miniQuanLyThongTin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        miniQuanLyThongTin.setForeground(new java.awt.Color(236, 114, 36));
        miniQuanLyThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/doctor.png"))); // NOI18N
        miniQuanLyThongTin.setText("Quản lý thông tin Nhân viên");
        miniQuanLyThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniQuanLyThongTinActionPerformed(evt);
            }
        });
        jMenu2.add(miniQuanLyThongTin);

        jMenuBar1.add(jMenu2);

        jMenu4.setForeground(new java.awt.Color(0, 0, 204));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/THongKe.png"))); // NOI18N
        jMenu4.setText("Thống kê");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miniNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        miniNhanVien.setForeground(new java.awt.Color(236, 114, 36));
        miniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/user.png"))); // NOI18N
        miniNhanVien.setText("Nhân Viên");
        miniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniNhanVienActionPerformed(evt);
            }
        });
        jMenu4.add(miniNhanVien);

        miniLuongThuCungKham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miniLuongThuCungKham.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        miniLuongThuCungKham.setForeground(new java.awt.Color(236, 114, 36));
        miniLuongThuCungKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/icon_luongthu cung.png"))); // NOI18N
        miniLuongThuCungKham.setText("Lượng Thú Cưng khám");
        miniLuongThuCungKham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniLuongThuCungKhamActionPerformed(evt);
            }
        });
        jMenu4.add(miniLuongThuCungKham);

        minibaocaothongke.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        minibaocaothongke.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        minibaocaothongke.setForeground(new java.awt.Color(236, 114, 36));
        minibaocaothongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Diagram.png"))); // NOI18N
        minibaocaothongke.setText("Báo cáo thống kê Doanh Thu");
        minibaocaothongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minibaocaothongkeActionPerformed(evt);
            }
        });
        jMenu4.add(minibaocaothongke);

        jMenuBar1.add(jMenu4);

        jMenu3.setForeground(new java.awt.Color(0, 0, 204));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/trợ giúp.png"))); // NOI18N
        jMenu3.setText("TRợ Gíup");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        minilienhe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_DOWN_MASK));
        minilienhe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        minilienhe.setForeground(new java.awt.Color(236, 114, 36));
        minilienhe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Telephone.png"))); // NOI18N
        minilienhe.setText("Liên hệ");
        minilienhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minilienheActionPerformed(evt);
            }
        });
        jMenu3.add(minilienhe);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDangnhapActionPerformed
        // TODO add your handling code here:
        //Mở lại form ĐĂNG NHẬP 
        this.DangXuat();
    }//GEN-LAST:event_miDangnhapActionPerformed

    private void miniphieukhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniphieukhamActionPerformed
        // TODO add your handling code here:
        //PHIÊÚ KHÁM MINI
        this.openPhieukham();
    }//GEN-LAST:event_miniphieukhamActionPerformed

    private void miniquanlithuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniquanlithuocActionPerformed
        // TODO add your handling code here:
        //QUẢN LÍ THUỐC
        this.openQlThuoc();
    }//GEN-LAST:event_miniquanlithuocActionPerformed

    private void blthongke2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blthongke2MouseClicked
      lbthongke1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //THỐNG KÊ
        this.openthongke(1);
    }//GEN-LAST:event_blthongke2MouseClicked

    private void lbhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbhoadonMouseClicked
        lbhoadon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //HÓA ĐƠN
        this.openHoadon();
    }//GEN-LAST:event_lbhoadonMouseClicked

    private void lbphieukhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbphieukhamMouseClicked
       lbphieukham.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //PHIÊÚ KHÁM
        this.openPhieukham();
    }//GEN-LAST:event_lbphieukhamMouseClicked

    private void lbquanlithongtinpetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbquanlithongtinpetMouseClicked
        lbhethongquanlipet.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //QUẢN LÍ THÔNG TIN pet
        this.openQLTTthucung();
    }//GEN-LAST:event_lbquanlithongtinpetMouseClicked

    private void lbquanlithuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbquanlithuocMouseClicked
        lbquanlithuoc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //QUẢN LÍ THUỐC MINI
        this.openQlThuoc();
    }//GEN-LAST:event_lbquanlithuocMouseClicked

    private void minibaocaothongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minibaocaothongkeActionPerformed
        // TODO add your handling code here:
        //BÁO CÁ THỐNG KÊ MINI
        this.openthongke(2);
    }//GEN-LAST:event_minibaocaothongkeActionPerformed

    private void minihoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minihoadonActionPerformed
        // TODO add your handling code here:
        //HÓA ĐƠN MINI
        this.openHoadon();
    }//GEN-LAST:event_minihoadonActionPerformed

    private void miniquanlithongtinpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniquanlithongtinpetActionPerformed
        // TODO add your handling code here:
        //QUẢN LÍ THÔNG TIN MINI
        this.openQLTTthucung();
    }//GEN-LAST:event_miniquanlithongtinpetActionPerformed

    private void miQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuenMatKhauActionPerformed
        // TODO add your handling code here:
        //ĐĂNG KÍ 
       this.openQuenMatKhau();
    }//GEN-LAST:event_miQuenMatKhauActionPerformed

    private void midoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midoimatkhauActionPerformed
        // TODO add your handling code here:
        //ĐỔI MẬT KHẨU 
        this.openDoiMatkhau();
    }//GEN-LAST:event_midoimatkhauActionPerformed

    private void midichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midichvuActionPerformed
        // TODO add your handling code here:
        //DỊCH VỤ 
        this.openDichvu(5);
    }//GEN-LAST:event_midichvuActionPerformed

    private void mikethucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mikethucActionPerformed
        // TODO add your handling code here:
        //KẾT THÚC 
          System.exit(0);
    }//GEN-LAST:event_mikethucActionPerformed

    private void minilienheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minilienheActionPerformed
        // TODO add your handling code here:
        //LIÊN HỆ 
        this.openLienhe();
    }//GEN-LAST:event_minilienheActionPerformed

    private void lbthongke1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbthongke1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbthongke1MouseEntered

    private void lbthongke1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbthongke1MouseClicked
   //   lbthongke1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //THỐNG KÊ IMAGE
        this.openthongke(0);
    }//GEN-LAST:event_lbthongke1MouseClicked

    private void lblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseClicked
 //lblHoaDon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.openHoadon();
    }//GEN-LAST:event_lblHoaDonMouseClicked

    private void lblPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamMouseClicked
   //     lblPhieuKham.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //PHIẾU KHÁM IMAGE
        this.openPhieukham();
    }//GEN-LAST:event_lblPhieuKhamMouseClicked

    private void lblThuCungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuCungMouseClicked
  //      lblThuCung.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //QUẢN LÍ THÔNG TIN PET IMAGE
        this.openQLTTthucung();
    }//GEN-LAST:event_lblThuCungMouseClicked

    private void lblQunaLyThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQunaLyThuocMouseClicked
   //    lblQunaLyThuoc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //QUẢN LÍ THUỐC IMAGE
        this.openQlThuoc();
    }//GEN-LAST:event_lblQunaLyThuocMouseClicked

    private void midoimatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midoimatkhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_midoimatkhauMouseClicked

    private void miniLuongThuCungKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniLuongThuCungKhamActionPerformed
        this.openthongke(1);
    }//GEN-LAST:event_miniLuongThuCungKhamActionPerformed

    private void miniQuanLyThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniQuanLyThongTinActionPerformed
        this.openQuanliThongTin();
    }//GEN-LAST:event_miniQuanLyThongTinActionPerformed

    private void miniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniNhanVienActionPerformed
        this.openthongke(0);
    }//GEN-LAST:event_miniNhanVienActionPerformed

    private void btnkhamdinhkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhamdinhkiActionPerformed
        this.openDichvu(0);
    }//GEN-LAST:event_btnkhamdinhkiActionPerformed

    private void btnphauthuatchomeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphauthuatchomeoActionPerformed
       this.openDichvu(1);
    }//GEN-LAST:event_btnphauthuatchomeoActionPerformed

    private void btnkhachsanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachsanActionPerformed
       this.openDichvu(2);
    }//GEN-LAST:event_btnkhachsanActionPerformed

    private void btnrangmiengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrangmiengActionPerformed
      this.openDichvu(3);
    }//GEN-LAST:event_btnrangmiengActionPerformed

    private void btncapcuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapcuuActionPerformed
        this.openDichvu(4);
    }//GEN-LAST:event_btncapcuuActionPerformed

    private void lbthongke1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbthongke1MouseMoved
       lbthongke1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbthongke1MouseMoved

    private void blthongke2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blthongke2MouseMoved
       blthongke2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_blthongke2MouseMoved

    private void lblHoaDonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseMoved
        lblHoaDon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblHoaDonMouseMoved

    private void lbhoadonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbhoadonMouseMoved
        lbhoadon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbhoadonMouseMoved

    private void lblPhieuKhamMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuKhamMouseMoved
       lblPhieuKham.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblPhieuKhamMouseMoved

    private void lbphieukhamMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbphieukhamMouseMoved
      lbphieukham.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbphieukhamMouseMoved

    private void lblThuCungMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuCungMouseMoved
       lblThuCung.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblThuCungMouseMoved

    private void lbquanlithongtinpetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbquanlithongtinpetMouseMoved
     lbquanlithongtinpet.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbquanlithongtinpetMouseMoved

    private void lblQunaLyThuocMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQunaLyThuocMouseMoved
      lblQunaLyThuoc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblQunaLyThuocMouseMoved

    private void lbquanlithuocMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbquanlithuocMouseMoved
      lbquanlithuoc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lbquanlithuocMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_HeThongChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_HeThongChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_HeThongChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_HeThongChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_HeThongChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blthongke2;
    private javax.swing.JButton btncapcuu;
    private javax.swing.JButton btnkhachsan;
    private javax.swing.JButton btnkhamdinhki;
    private javax.swing.JButton btnphauthuatchomeo;
    private javax.swing.JButton btnrangmieng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbhethongquanlipet;
    private javax.swing.JLabel lbhoadon;
    private javax.swing.JLabel lblDangHoatDong;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblPhieuKham;
    private javax.swing.JLabel lblQunaLyThuoc;
    private javax.swing.JLabel lblThuCung;
    private javax.swing.JLabel lbphieukham;
    private javax.swing.JLabel lbquangliphongkhampet;
    private javax.swing.JLabel lbquanlithongtinpet;
    private javax.swing.JLabel lbquanlithuoc;
    private javax.swing.JLabel lbthongke1;
    private javax.swing.JMenuItem miDangnhap;
    private javax.swing.JMenuItem miQuenMatKhau;
    private javax.swing.JMenuItem midichvu;
    private javax.swing.JMenuItem midoimatkhau;
    private javax.swing.JMenuItem mikethuc;
    private javax.swing.JMenuItem miniLuongThuCungKham;
    private javax.swing.JMenuItem miniNhanVien;
    private javax.swing.JMenuItem miniQuanLyThongTin;
    private javax.swing.JMenuItem minibaocaothongke;
    private javax.swing.JMenuItem minihoadon;
    private javax.swing.JMenuItem minilienhe;
    private javax.swing.JMenuItem miniphieukham;
    private javax.swing.JMenuItem miniquanlithongtinpet;
    private javax.swing.JMenuItem miniquanlithuoc;
    private javax.swing.JPanel pnlHoaDon;
    // End of variables declaration//GEN-END:variables
  private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(ImageHelper.getAppIcon());

        setSize(1000, 600);
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat ft = new SimpleDateFormat("hh:mm:ss a");
                String text = ft.format(now);
                lblDongHo.setText(text);

            }
        }).start();;
        new ChaoJdialog(this, true).setVisible(true);
        new DangNhapJdialog(this, true).setVisible(true);
    }
    ////////

    //------------------openThongKe(int index)-------------------------------------------------
    private void openthongke(int index1) {

        if (Auth.isLogin()) {
            if (index1 == 2 && !Auth.isManager()) {
                MsgBox.alert(this, "Nhân viên không có quyền xem thông tin doanh thu!");
            } else {
                BaoCaoThongKeDialog tk = new BaoCaoThongKeDialog(this, true);
                tk.selectTab(index1);
                tk.setVisible(true);

            }

        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

//    void openthongke() {       
//            new BaoCaoThongKeDialog(this, true).setVisible(true);
//       }
    void openQlThuoc() {
        new ThuocDialog(this, true).setVisible(true);
    }

    void openQLTTthucung() {
        new QuanLyThuCung(this, true).setVisible(true);
    }

    void openPhieukham() {
        new LapPhieuKhamJdialog(this, true).setVisible(true);
    }

    void openHoadon() {
        new HoaDonDialog(this, true).setVisible(true);
    }

    private void openDichvu(int index2) {
        new DichvuDialog(this, true).setVisible(true);
    }

    void openQuenMatKhau() {
        new QuenMatKhauJDialog(this, true).setVisible(true);
    }

    void openChao() {
        new ChaoJdialog(this, true).setVisible(true);
    }

    void openDoiMatkhau() {
        new doimatKhauJDialog(this, true).setVisible(true);
    }

    void openDangnhap() {
        new DangNhapJdialog(this, true).setVisible(true);
    }

    void openLienhe() {
        new LienheDialog(this, true).setVisible(true);
    }

    void openQuanliThongTin() {
        new QuanLyThongTinNhanVien(this, true).setVisible(true);
    }

    //------------------Đăng xuất-------------------------------------------------
    private void DangXuat() {
        Auth.clear();
        new DangNhapJdialog(this, true).setVisible(true);

    }

    //------------------KetThuc-------------------------------------------------
    private void KetThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kêt thúc Làm việc!")) {
            System.exit(0);
        }
    }
}
