/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_QLPKThuCung;


import TienIch.ImageHelper;
import TienIch.MsgBox;
import TienIch.XDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Dao.HoaDonPKDAO;
import Class_entity.HoaDonPK;
import TienIch.Auth;
import static TienIch.ValidateHelper.Black;
import static TienIch.ValidateHelper.Color;
import static TienIch.ValidateHelper.Gray;
import static TienIch.ValidateHelper.Italic;
import static TienIch.ValidateHelper.Plain;
import java.awt.Color;

/**
 *
 * @author minh
 */
public class HoaDonDialog extends javax.swing.JDialog {

    /**
     * Creates new form HoaDonDialog
     * @param parent
     * @param modal
     */
    public HoaDonDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.init();
    }
int index = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLapNgay = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtMaTC = new javax.swing.JTextField();
        txtthanhtien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangHoaDon = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnXuatBill = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        lblSoHoaDon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(158, 235, 241));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("HÓA ĐƠN PHÒNG KHÁM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Số Hóa Đơn:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Lập Ngày:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Mã NV:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Mã Thú Cưng:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Thành Tiên:");

        txtLapNgay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLapNgay.setForeground(new java.awt.Color(153, 153, 153));
        txtLapNgay.setText("VD:16/04/2017");
        txtLapNgay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLapNgayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLapNgayFocusLost(evt);
            }
        });

        tblBangHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SỐ HÓA ĐƠN", "NGÀY LẬP HÓA ĐƠN", "Mã Nhân Viên", "MÃ Thú Cưng", "THÀNH TIỀN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangHoaDon.setRowHeight(25);
        tblBangHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangHoaDon);

        btnThem.setBackground(new java.awt.Color(0, 102, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/thêm.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 102, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/xóa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 102, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/sữa.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(0, 102, 0));
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Mới.png"))); // NOI18N
        btnNew.setText("Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(255, 204, 204));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Button-First-icon.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(255, 204, 204));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/prev.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(255, 204, 204));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/next.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(255, 204, 204));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Button-Last-icon.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnXuatBill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuatBill.setForeground(new java.awt.Color(0, 102, 102));
        btnXuatBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/print_anh.png"))); // NOI18N
        btnXuatBill.setText("In Hóa Đơn");
        btnXuatBill.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnXuatBillItemStateChanged(evt);
            }
        });
        btnXuatBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBillActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(158, 235, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 102))); // NOI18N

        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane2.setViewportView(txtBill);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        lblSoHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSoHoaDon.setForeground(new java.awt.Color(255, 51, 0));
        lblSoHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoHoaDon.setPreferredSize(new java.awt.Dimension(34, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNV)
                            .addComponent(txtMaTC)
                            .addComponent(txtthanhtien)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLapNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblSoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 43, Short.MAX_VALUE)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXuatBill, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLapNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNew))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFirst)
                            .addComponent(btnPrev)
                            .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLast, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuatBill)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       if(Check_Form()){
        this.update();
       }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       if(Check_Form()){
        this.insert();
       }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
   //tblBangHoaDon.changeSelection(tblBangHoaDon.getRowCount()-1, 0, false, false);
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
   // tblBangHoaDon.changeSelection(index++, 0, false, false);
       
        this.prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
   // tblBangHoaDon.changeSelection(index++, 0, false, false);
     
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
 //  tblBangHoaDon.changeSelection(tblBangHoaDon.getRowCount()-1, 0, false, false);
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblBangHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangHoaDonMouseClicked
     
      
        if (evt.getClickCount() == 2) {// (2):nhấndup 2 làn hien len 
            this.row = tblBangHoaDon.getSelectedRow();
            this.edit();
             txtMaTC.setEnabled(false);
            txtMaNV.setEnabled(false);

        }
    }//GEN-LAST:event_tblBangHoaDonMouseClicked

    private void btnXuatBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBillActionPerformed
String S = lblSoHoaDon.getText();
String N = txtLapNgay.getText();
String MaNV = txtMaNV.getText();
String MaTC = txtMaTC.getText();
String TT = txtthanhtien.getText();
        
txtBill.setText(txtBill.getText() +"*******************************************************\n*");
txtBill.setText(txtBill.getText() +"\t\n*" + "=>Số Hóa Đơn : " +S +                       "\n*");
txtBill.setText(txtBill.getText() +"\t\n*" + "=>Ngày lập đơn : " +N +                     "\n*");
txtBill.setText(txtBill.getText() +"\t\n*" + "=>Nhân viên lập phiếu : " + MaNV +          "\n*");
txtBill.setText(txtBill.getText() +"\t\n*" + "=>Mã Thú cưng : " + MaTC +                  "\n*");
txtBill.setText(txtBill.getText() +"\t\n*" + "=>Thành Tiền : " + TT +"VNĐ"+               "\n*");
txtBill.setText(txtBill.getText() +"*******************************************************\n*");

    }//GEN-LAST:event_btnXuatBillActionPerformed

    private void btnXuatBillItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnXuatBillItemStateChanged
       
    }//GEN-LAST:event_btnXuatBillItemStateChanged

    private void txtLapNgayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLapNgayFocusGained
       if (txtLapNgay.getForeground().equals(Gray)) {
            Color(txtLapNgay, "", Plain, Black);
        }
    }//GEN-LAST:event_txtLapNgayFocusGained

    private void txtLapNgayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLapNgayFocusLost
       if (txtLapNgay.getText().trim().isEmpty()) {
            Color(txtLapNgay, "VD: 16/04/2018 ", Italic, Gray);
        }
        
        
    }//GEN-LAST:event_txtLapNgayFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoaDonDialog dialog = new HoaDonDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSoHoaDon;
    private javax.swing.JTable tblBangHoaDon;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtLapNgay;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaTC;
    private javax.swing.JTextField txtthanhtien;
    // End of variables declaration//GEN-END:variables

    
    HoaDonPKDAO dao = new HoaDonPKDAO();
     int row = -1;
    public void init() {
        this.setLocationRelativeTo(null); // đưa cửa sổ ra giữa màn hình
        this.setTitle("HÓA ĐƠN PHÒNG KHÁM");
        this.setIconImage(ImageHelper.getAppIcon());
        this.fillTable();
        this.updateStatus();
        txtMaNV.setText(Auth.user.getMaNV());
        txtMaNV.setEditable(false);

//        txtMaNV.setEnabled(true);
//        txtMaTC.setEnabled(true);
        this.row = -1;
    }

   void fillTable() {//Đỗ dữ liệu vào bảng tblHocViẹn

        DefaultTableModel model = (DefaultTableModel) tblBangHoaDon.getModel();
        model.setRowCount(0);// xóa tất cả các hàng trên Jtable
        try {

            List<HoaDonPK> list = dao.selectAll();// đọc cơ sở dữ liệu//selectALL:duyệt toàn bộ nhân viên

            for (HoaDonPK HDPK : list) {
                Object[] row = {
                    HDPK.getMaHD(),
                    XDate.toString(HDPK.getNgayHD(), "dd/MM/yyyy"),
                    HDPK.getMaNV(),
                    HDPK.getMaTC(),
                    HDPK.getDonGia(),};
                model.addRow(row);// Thêm một hàng vào Jtable
            }

        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
   
   //--------------
     void clearForm() {
        HoaDonPK HDPK = new HoaDonPK();
        HDPK.setMaNV(Auth.user.getMaNV());
        this.setForm(HDPK);
        txtLapNgay.setText("");
        btnThem.setEnabled(true);
        txtMaTC.setText("");
        txtMaNV.setEditable(false);
        txtthanhtien.setText("");
//        txtMaNV.setEditable(true);
        //
        txtMaTC.setEnabled(true);
        txtMaTC.setEditable(true);

    }

    void setForm(HoaDonPK HDPK) {
        
        lblSoHoaDon.setText(HDPK.getMaHD());
        txtLapNgay.setText(XDate.toString(HDPK.getNgayHD()));
        txtMaNV.setText(HDPK.getMaNV());
        txtMaTC.setText(HDPK.getMaTC());
        txtthanhtien.setText(String.valueOf(String.format("%.0f",HDPK.getDonGia())));
    }

    HoaDonPK getForm() {
        // 
        HoaDonPK HDPK = new HoaDonPK();
        HDPK.setMaHD(lblSoHoaDon.getText());
        HDPK.setNgayHD(XDate.toDate(txtLapNgay.getText()));
        HDPK.setMaNV(txtMaNV.getText());
        HDPK.setMaTC(txtMaTC.getText());
        HDPK.setDonGia(Double.valueOf(txtthanhtien.getText()));
        return HDPK;

    }
        void edit() {
        String MaHD = (String) tblBangHoaDon.getValueAt(this.row, 0);
        HoaDonPK HDPK = dao.selectById(MaHD);
        this.setForm(HDPK);
        this.updateStatus();
      
    }

    void first() {
        this.row = 0;
        MsgBox.alert(this, "Đang ở đầu !");
        this.edit();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {
        if (this.row < tblBangHoaDon.getRowCount() - 1) {
            this.row++;
            this.edit();
            
        }
        else if(this.row < tblBangHoaDon.getRowCount() - 1){
            this.row++;
            this.edit();
        }
    }

    void last() {
        this.row = tblBangHoaDon.getRowCount() - 1;
        this.edit();
        MsgBox.alert(this, "Đang ở cuối !");
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblBangHoaDon.getRowCount() - 1);
        // Trạng thái form
        txtMaTC.setEditable(!edit);
        txtMaNV.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);

        // Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    void insert() {
        HoaDonPK HDPK = getForm();
        try {
            dao.insert(HDPK);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    void update() {
        HoaDonPK HDPK = getForm();
        try {
            dao.update(HDPK);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không quyền xoá Thú cưng");
        } else if (MsgBox.confirm(this, "Bạn thực sự muốn xoá Thú cưng này?")) {
            try {
                String maHD = lblSoHoaDon.getText();
                dao.delete(maHD);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xoá thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Xoá thất bại");
            }

        }// 
    }
///-----------Check_Form------------------------
    
    public boolean Check_Form(){
        if(txtLapNgay.getText().equals("")){
            txtLapNgay.requestFocus();
            MsgBox.alert(this, "Bạn vui lòng nhập Ngày lập!");
            txtLapNgay.setBackground(Color.YELLOW);
            return false;
        }else{
            txtLapNgay.setBackground(Color.white);
        }
        if ((txtLapNgay.getText().length() != 10)) {
            txtLapNgay.requestFocus();
            txtLapNgay.setBackground(Color.yellow);
                MsgBox.alert(this, "Định dạng ngày nhập vào chưa chính xác!");
                return false;
            }else{
            txtLapNgay.setBackground(Color.white);
        }
        if(txtMaNV.getText().equals("")){
            txtMaNV.requestFocus();
            MsgBox.alert(this, "Bạn vui lòng nhập Mã nhân viên!");
            txtMaNV.setBackground(Color.YELLOW);
            return false;
        }else{
            txtMaNV.setBackground(Color.white);
        }
        if(txtMaTC.getText().equals("")){
            txtMaTC.requestFocus();
            MsgBox.alert(this, "Bạn vui lòng nhập Mã thú cưng!");
            txtMaTC.setBackground(Color.YELLOW);
            return false;
        }else{
            txtMaTC.setBackground(Color.white);
        }
         
        if(txtthanhtien.getText().equals("")){
            txtthanhtien.requestFocus();
            MsgBox.alert(this, "Bạn vui lòng nhập số Tiền!");
            txtthanhtien.setBackground(Color.YELLOW);
            return false;
        }else{
            txtthanhtien.setBackground(Color.white);
        }
          try {
            double Tien = Double.parseDouble(txtthanhtien.getText());
        } catch (NumberFormatException e) {
           MsgBox.alert(this, "Thành tiền Phải Là Số !!!");
            txtthanhtien.setBackground(Color.yellow);
            txtthanhtien.setText("");
            txtthanhtien.requestFocus();
            return false;
        }
        
        return true;
    }
    
}
