/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Form_QLPKThuCung;

import Class_entity.NhanVien;
import TienIch.MsgBox;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import TienIch.*;
import java.awt.HeadlessException;

import java.util.Properties;
import java.util.Random;

import javax.mail.Message;
import javax.mail.MessagingException;

import javax.mail.Session;
import javax.mail.Transport;

import javax.mail.internet.InternetAddress;

import javax.mail.internet.MimeMessage;

import javax.swing.JOptionPane;
import Dao.NhanVienDao;
import javax.swing.ImageIcon;
import static TienIch.ColorHelper.setBackround;
import java.awt.Color;



/**
 *
 * @author User
 */
public class QuenMatKhauJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhauJDialog
     */
    private static String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private static String dburl = "jdbc:sqlserver://localhost:1433;database=QLPKTC_Nhom06";
    private static String username1 = "sa";
    private static String password = "songlong";

    Connection con1 = null;
    ResultSet rs1 = null;
    PreparedStatement pst = null;

    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    String email;
    int randomCode;

    NhanVien nv1 = new NhanVien();

    public String MaNV;

    public QuenMatKhauJDialog(String username) {
        this.MaNV = username;
        //initComponents();
        this.init();
    }

    public void init() {
        // txtEmail.setText("thangthanh7979@gmail.com");

        this.setIconImage(ImageHelper.getAppIcon());
        this.setLocationRelativeTo(null);
        txtTen.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cboshowpass = new javax.swing.JCheckBox();
        lblEmail = new javax.swing.JLabel();
        lblcode = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        lblMatKhauMoi = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCauHoiBiMat = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnKiemTraCode = new javax.swing.JButton();
        lblxacNhanMatKhau = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtXacnhanMK = new javax.swing.JPasswordField();
        lblCheck = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quên Mật Khẩu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboshowpass.setBackground(new java.awt.Color(204, 255, 204));
        cboshowpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Eye-2-icon.png"))); // NOI18N
        cboshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboshowpassActionPerformed(evt);
            }
        });
        jPanel3.add(cboshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 51, 0));
        lblEmail.setText("Email :");
        jPanel3.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 28, -1, -1));

        lblcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcode.setForeground(new java.awt.Color(102, 51, 0));
        lblcode.setText("Code :");
        jPanel3.add(lblcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, -1, -1));

        lblTenNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(102, 51, 0));
        lblTenNV.setText("Tên đăng nhâp :");
        jPanel3.add(lblTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 109, -1, -1));

        lblMatKhauMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMatKhauMoi.setForeground(new java.awt.Color(102, 51, 0));
        lblMatKhauMoi.setText("mật khẩu mới :");
        jPanel3.add(lblMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 160, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setPreferredSize(new java.awt.Dimension(139, 25));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 25, 236, -1));

        txtCauHoiBiMat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCauHoiBiMat.setForeground(new java.awt.Color(153, 153, 153));
        txtCauHoiBiMat.setPreferredSize(new java.awt.Dimension(75, 25));
        txtCauHoiBiMat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCauHoiBiMatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCauHoiBiMatFocusLost(evt);
            }
        });
        txtCauHoiBiMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCauHoiBiMatActionPerformed(evt);
            }
        });
        txtCauHoiBiMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCauHoiBiMatKeyReleased(evt);
            }
        });
        jPanel3.add(txtCauHoiBiMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 66, 185, -1));

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTen.setForeground(new java.awt.Color(153, 153, 153));
        txtTen.setPreferredSize(new java.awt.Dimension(49, 25));
        txtTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenFocusLost(evt);
            }
        });
        txtTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenMouseClicked(evt);
            }
        });
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });
        jPanel3.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 106, 185, -1));

        btnluu.setBackground(new java.awt.Color(204, 255, 204));
        btnluu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnluu.setForeground(new java.awt.Color(0, 153, 102));
        btnluu.setText("Lưu");
        btnluu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnluuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnluuMouseExited(evt);
            }
        });
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });
        jPanel3.add(btnluu, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 227, 73, -1));

        btnLogin.setBackground(new java.awt.Color(204, 255, 204));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 153, 102));
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 227, 73, -1));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 153, 102));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/Search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSearchFocusLost(evt);
            }
        });
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 24, 110, -1));

        btnKiemTraCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKiemTraCode.setForeground(new java.awt.Color(0, 153, 102));
        btnKiemTraCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/tích xanh check.png"))); // NOI18N
        btnKiemTraCode.setText("check");
        btnKiemTraCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnKiemTraCodeFocusGained(evt);
            }
        });
        btnKiemTraCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKiemTraCodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKiemTraCodeMouseExited(evt);
            }
        });
        btnKiemTraCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraCodeActionPerformed(evt);
            }
        });
        jPanel3.add(btnKiemTraCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 65, 110, -1));

        lblxacNhanMatKhau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblxacNhanMatKhau.setForeground(new java.awt.Color(102, 51, 0));
        lblxacNhanMatKhau.setText("Xác nhận mật khẩu :");
        jPanel3.add(lblxacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 199, -1, -1));

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpass.setForeground(new java.awt.Color(153, 153, 153));
        txtpass.setPreferredSize(new java.awt.Dimension(21, 25));
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassFocusLost(evt);
            }
        });
        jPanel3.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 157, 185, -1));

        txtXacnhanMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtXacnhanMK.setForeground(new java.awt.Color(153, 153, 153));
        txtXacnhanMK.setPreferredSize(new java.awt.Dimension(21, 25));
        txtXacnhanMK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtXacnhanMKFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtXacnhanMKFocusLost(evt);
            }
        });
        txtXacnhanMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtXacnhanMKKeyReleased(evt);
            }
        });
        jPanel3.add(txtXacnhanMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 196, 236, -1));

        lblCheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblCheckKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblCheckKeyReleased(evt);
            }
        });
        jPanel3.add(lblCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 196, 33, 20));

        btnHuy.setBackground(new java.awt.Color(204, 255, 204));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(0, 153, 102));
        btnHuy.setText("Hủy");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHuyMouseExited(evt);
            }
        });
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel3.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 227, 73, -1));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 30, 30));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9, 95, 49), 1, true));
        jLabel8.setOpaque(true);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 260));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Anh/banerQMK.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        setSize(new java.awt.Dimension(649, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCheckKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblCheckKeyReleased

    }//GEN-LAST:event_lblCheckKeyReleased

    private void lblCheckKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblCheckKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCheckKeyPressed

    private void txtXacnhanMKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtXacnhanMKKeyReleased
        String passwork = txtpass.getText();
        String passwork1 = txtXacnhanMK.getText();
        if (!passwork.equals(passwork1)) {
            lblCheck.setIcon(new ImageIcon("src\\Image\\icon\\x đăng ký.png"));        // TODO add your handling code here:
          //  MsgBox.alert(this, "Hai mật khẩu không trùng khớp , làm ơn kiểm tra lại !");
        } else {
            lblCheck.setIcon(new ImageIcon("src\\Image\\icon\\tích xanh check.png"));
        }
    }//GEN-LAST:event_txtXacnhanMKKeyReleased

    private void btnKiemTraCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraCodeActionPerformed
        if (check_so()) {

            if (Integer.valueOf(txtCauHoiBiMat.getText()) == randomCode) {
                MsgBox.alert(null, "mã code đúng!");
                jLabel6.setIcon(new ImageIcon("src\\Image\\icon\\tích xanh check.png"));
                txtTen.setEnabled(true);
                // TODO add your handling code here:

            }  else {
                MsgBox.alert(null, "Mã code sai !");
                jLabel6.setIcon(new ImageIcon("src\\Image\\icon\\x đăng ký.png"));

            }
        }
    }//GEN-LAST:event_btnKiemTraCodeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (kiemtra_mail()) {
            try {
                //  System.setProperty("java.protocol.handler.pkgs", "com.sun.net.ssl.internal.www.protocol");
                //
                //        URL url = new URL("https://www.gmail.com");
                Random rand = new Random();

                randomCode = rand.nextInt(999999);

                String host = "smtp.gmail.com";

                String user = "thangttps16989@fpt.edu.vn";

                String pass = "happy2002";

                String to = txtEmail.getText();

                String subject = "Reseting Code";

                String message = "code reset cuabạn là: " + randomCode;
                boolean sessionDebug = false;
                Properties pros = System.getProperties();
                pros.put("mail.smtp.auth", "true");
                pros.put("mail.smtp.starttls.enable", "true");
                pros.put("mail.smtp.host", "smtp.gmail.com");
                pros.put("mail.smtp.port", 587);
                String accountName = txtEmail.getText();
                String accountPass = txtpass.getText();
                Session s = Session.getInstance(pros,
                        new javax.mail.Authenticator() {
                    protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                        return new javax.mail.PasswordAuthentication(accountName, accountPass);
                    }
                });
                //JavaMailSenderImpl mailSender = new org.springframework.mail.javamail.JavaMailSenderImpl();
                //java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                System.setProperty("java.protocol.handler.pkgs", "com.sun.net.ssl.internal.www.protocol");

                Session mailSession = Session.getDefaultInstance(pros, null);

                mailSession.setDebug(sessionDebug);

                Message msg = new MimeMessage(mailSession);

                msg.setFrom(new InternetAddress(user));

                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));

                msg.setSubject(subject);

                msg.setText(message);

                Transport transport = mailSession.getTransport("smtp");

                transport.connect(host, user, pass);

                transport.sendMessage(msg, msg.getAllRecipients());

                transport.close();
     new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    
                }
               
            }
        }).start();
//    WaitingJDialog wai = new WaitingJDialog(null,rootPaneCheckingEnabled);
//        wai.setVisible(true);
                JOptionPane.showMessageDialog(null, "mã đã được gửi đến email");

            } catch (HeadlessException | MessagingException ex) {

                JOptionPane.showMessageDialog(null, "Mail lỗi !!!", "Vui lòng nhập lại !", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
this.dispose();
        DangNhapJdialog dn = new DangNhapJdialog(null, rootPaneCheckingEnabled);
        dn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        if (check_Form()) {
            //   JOptionPane.showMessageDialog(this, "nhap du thong tin");

            checkemail_TenNV();

            if (txtpass.getText().equals(txtXacnhanMK.getText())) {
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String updatequery = "update NhanVien set Matkhau=? where MaNV=?";
                    con1 = DriverManager.getConnection(dburl, username1, password);
                    pst = con1.prepareStatement(updatequery);
                    pst.setString(1, txtXacnhanMK.getText());
                    pst.setString(2, txtTen.getText());
                    int kq = pst.executeUpdate();
                    con1.close();
                    pst.close();
                    if (kq > 0) {
                        JOptionPane.showMessageDialog(this, "UpDate Thànnh Công !");
                        System.out.println("Update thành công");
                    } else {
                        JOptionPane.showMessageDialog(this, "UpDate  Thất Bại !");
                        System.out.println("Update không thành công");
                    }
                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(this, "ERRO!!!", "Please input agian !", JOptionPane.ERROR_MESSAGE);

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "mật khẩu ko khớp!");
            }
        }
    }//GEN-LAST:event_btnluuActionPerformed

    private void txtCauHoiBiMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCauHoiBiMatKeyReleased

    }//GEN-LAST:event_txtCauHoiBiMatKeyReleased

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed

    }//GEN-LAST:event_txtEmailActionPerformed

    private void cboshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboshowpassActionPerformed
        if (cboshowpass.isSelected()) {
            txtpass.setEchoChar((char) 0);
            txtXacnhanMK.setEchoChar((char) 0);
        } else {
            txtpass.setEchoChar('*');
            txtXacnhanMK.setEchoChar('*');
        }
    }//GEN-LAST:event_cboshowpassActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
////if (txtEmail.getForeground().equals(Gray)) {
////            Color(txtEmail, "", Plain, Black);
////        }
////        
////           
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
//        if (txtEmail.getText().trim().isEmpty()) {
//            Color(txtEmail, "VD: PS16989@gmail.com ", Italic, Gray);
//        } 
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtCauHoiBiMatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCauHoiBiMatFocusGained
//       if (txtCauHoiBiMat.getForeground().equals(Gray)) {
//            Color(txtCauHoiBiMat, "", Plain, Black);
//        }
    }//GEN-LAST:event_txtCauHoiBiMatFocusGained

    private void txtCauHoiBiMatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCauHoiBiMatFocusLost
//       if (txtCauHoiBiMat.getText().trim().isEmpty()) {
//            Color(txtCauHoiBiMat, "VD: ***** ", Italic, Gray);
//        } 
    }//GEN-LAST:event_txtCauHoiBiMatFocusLost

    private void txtTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusGained
//      if (txtTen.getForeground().equals(Gray)) {
//            Color(txtTen, "", Plain, Black);
//        }
    }//GEN-LAST:event_txtTenFocusGained

    private void txtTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenFocusLost
//        if (txtTen.getText().trim().isEmpty()) {
//            Color(txtTen, "VD: NV108 ", Italic, Gray);
//        } 
    }//GEN-LAST:event_txtTenFocusLost

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
//        if (txtpass.getForeground().equals(Gray)) {
//            Color(txtpass, "", Plain, Black);
//        }
    }//GEN-LAST:event_txtpassFocusGained

    private void txtpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusLost
//        if (txtpass.getText().trim().isEmpty()) {
//            Color(txtpass, "VD:*******", Italic, Gray);
//        }  
    }//GEN-LAST:event_txtpassFocusLost

    private void txtXacnhanMKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXacnhanMKFocusGained
//       if (txtXacnhanMK.getForeground().equals(Gray)) {
//            Color(txtXacnhanMK, "", Plain, Black);
//        }
    }//GEN-LAST:event_txtXacnhanMKFocusGained

    private void txtXacnhanMKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXacnhanMKFocusLost
//        if (txtXacnhanMK.getText().trim().isEmpty()) {
//            Color(txtXacnhanMK, "VD:*******", Italic, Gray);
//        } 
    }//GEN-LAST:event_txtXacnhanMKFocusLost

    private void btnluuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnluuMouseEntered
        setBackround(new Color(255, 204, 204), Color.white, btnluu);
    }//GEN-LAST:event_btnluuMouseEntered

    private void btnluuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnluuMouseExited
        setBackround(new Color(0, 102, 0), Color.white, btnluu);
    }//GEN-LAST:event_btnluuMouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        setBackround(new Color(255, 204, 204), Color.white, btnLogin);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        setBackround(new Color(0, 102, 0), Color.white, btnLogin);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSearchFocusGained

    }//GEN-LAST:event_btnSearchFocusGained

    private void btnSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSearchFocusLost

    }//GEN-LAST:event_btnSearchFocusLost

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
//       setBackround(new Color(255,204,204), Color.white, btnSearch);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        setBackround(new Color(0, 102, 0), Color.white, btnSearch);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnKiemTraCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnKiemTraCodeFocusGained

    }//GEN-LAST:event_btnKiemTraCodeFocusGained

    private void btnKiemTraCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKiemTraCodeMouseEntered
        setBackround(new Color(255, 204, 204), Color.white, btnKiemTraCode);
    }//GEN-LAST:event_btnKiemTraCodeMouseEntered

    private void btnKiemTraCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKiemTraCodeMouseExited
        setBackround(new Color(0, 102, 0), Color.white, btnKiemTraCode);
    }//GEN-LAST:event_btnKiemTraCodeMouseExited

    private void txtTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenMouseClicked

    }//GEN-LAST:event_txtTenMouseClicked

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed

    }//GEN-LAST:event_txtTenActionPerformed

    private void txtCauHoiBiMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCauHoiBiMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCauHoiBiMatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
       if(MsgBox.confirm(this, "Bạn có muốn kết thúc ứng dụng?")){
            System.exit(0);
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseExited
        setBackround(new Color(0, 102, 0), Color.white, btnHuy);
    }//GEN-LAST:event_btnHuyMouseExited

    private void btnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseEntered
        setBackround(new Color(255, 204, 204), Color.white, btnHuy);
    }//GEN-LAST:event_btnHuyMouseEntered
    NhanVienDao dao1 = new NhanVienDao();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnKiemTraCode;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnluu;
    private javax.swing.JCheckBox cboshowpass;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblcode;
    private javax.swing.JLabel lblxacNhanMatKhau;
    private javax.swing.JTextField txtCauHoiBiMat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtTen;
    private javax.swing.JPasswordField txtXacnhanMK;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables

    NhanVienDao dao = new NhanVienDao();

    public void checkemail_TenNV() {
        String manv = txtTen.getText().trim();
        String Email2 = txtEmail.getText().trim();
        NhanVien nhanVien = dao.selectById(manv);
        if (nhanVien == null) {
            MsgBox.alert(this, "Sai tên đăng nhập!");
        }

    }

    //---
    boolean check_so() {
        if (txtCauHoiBiMat.getText().equals("")) {
            txtCauHoiBiMat.setBackground(Color.yellow);
            MsgBox.alert(this, "Bạn chưa nhập mã code");
            jLabel6.setIcon(new ImageIcon("src\\Image\\icon\\x đăng ký.png"));
            txtCauHoiBiMat.setForeground(Color.BLUE);

            return false;
        }else {
            txtCauHoiBiMat.setBackground(Color.white);
            jLabel6.setIcon(new ImageIcon("src\\Image\\icon\\tích xanh check.png"));
        }
        
        if (txtCauHoiBiMat.getText().length() < 6) {
            jLabel6.setIcon(new ImageIcon("src\\Image\\icon\\x đăng ký.png"));
            MsgBox.alert(this, "Mã code phải nhập đủ 6 số!");
            txtCauHoiBiMat.requestFocus();
            return false;
        } else {
            txtCauHoiBiMat.setBackground(Color.white);
            jLabel6.setIcon(new ImageIcon("src\\Image\\icon\\tích xanh check.png"));
        }

        return true;
    }

    ////-------------check form()--------------------------------------------------
    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    public static boolean verifyEmail(String email) {
        if (email == null) {
            return false;
        }
        return email.matches(EMAIL_PATTERN);
    }

    public boolean kiemtra_mail() {
        if (txtEmail.getText().equals("")) {
            txtEmail.setBackground(Color.yellow);
            MsgBox.alert(this, "Bạn chưa nhập email!");
            txtEmail.setForeground(Color.BLUE);
            return false;
        } else {
            txtEmail.setBackground(Color.white);
        }
        if (verifyEmail(txtEmail.getText()) == false) {
            MsgBox.alert(this, "Định dạng email bạn nhập không chính xác");
            txtEmail.setForeground(Color.BLUE);
            return false;
        }
        return true;
    }

    public boolean check_Form() {
        if (txtEmail.getText().equals("")) {
            txtEmail.setBackground(Color.YELLOW);
            txtEmail.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập Tên Email !");
            return false;
        } else {
            txtEmail.setBackground(Color.WHITE);
        }
        if (txtCauHoiBiMat.getText().equals("")) {
            txtCauHoiBiMat.setBackground(Color.YELLOW);
            txtCauHoiBiMat.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Vui lòng NHập Mã code !");
            return false;
        } else {
            txtCauHoiBiMat.setBackground(Color.white);
        }
        if (txtTen.getText().equals("")) {
            txtTen.setBackground(Color.YELLOW);
            txtTen.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Vui lòng NHập Mã Nhân viên !");
            return false;
        } else {
            txtTen.setBackground(Color.WHITE);
        }
        if (txtpass.getText().equals("")) {
            txtpass.setBackground(Color.YELLOW);
            txtpass.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Vui lòng NHập Mật khẩu !");
            return false;
        } else {
            txtpass.setBackground(Color.WHITE);
        }
        if (txtXacnhanMK.getText().equals("")) {
            txtXacnhanMK.setBackground(Color.YELLOW);
            txtXacnhanMK.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập lại mật khẩu !");
            return false;
        } else {
            txtXacnhanMK.setBackground(Color.WHITE);
        }

        return true;
    }

}
